package net.exsource.css.help;

@SuppressWarnings("unsued")
public enum CssAttribute {

    ALIGN_CONTENT("align-content","Aligns items in a flex container along flex lines."),
    ALIGN_ITEMS("align-items","Aligns evenly spaced items in a flex container."),
    ALIGN_SELF("align-self","Aligns an item inside a flex container."),
    ALL("all","Resets all element properties to its default or inherited values."),
    ANIMATION("animation","Creates an animating element."),
    ANIMATION_DELAY("animation-delay","Sets a delay before an animation begins."),
    ANIMATION_DIRECTION("animation-direction","Sets how, in which direction, an animation is played."),
    ANIMATION_DURATION("animation-duration","Defines the duration of an animation cycle."),
    ANIMATION_FILL_MODE("animation-fill-mode","Defines how styles are applied before and after animation."),
    ANIMATION_INTERACTION_COUNT("animation-interaction-count","Sets the number of times an animation is played."),
    ANIMATION_NAME("animation-name","Defines a name for the animation."),
    ANIMATION_PLAY_STATE("animation-play-state","Sets the animation play state to running or paused."),
    ANIMATION_TIMING_FUNCTION("animation-timing-function","Specifies the animation speed curve."),
    BACKFACE_VISIBILITY("backface-visibility","Shows or hides the backface visibility of an element."),
    BACKGROUND("background","Sets the background of an element."),
    BACKGROUND_ATTACHMENT("background-attachment","Defines how the background is attached to an element."),
    BACKGROUND_BLEND_MODE("background-blend-mode","Defines the background layer blending mode."),
    BACKGROUND_CLIP("background-clip","Defines how background extends beyond the element."),
    BACKGROUND_COLOR("background-color","Sets the background color of the element."),
    BACKGROUND_IMAGE("background-image","Specifies a background image for an element."),
    BACKGROUND_ORIGIN("background-origin","Specifies the background image origin position."),
    BACKGROUND_POSITION("background-position","Sets the position of a background image."),
    BACKGROUND_REPEAT("background-repeat","Specifies how the background image is repeated."),
    BACKGROUND_SIZE("background-size","Sets the size of the background image."),
    BORDER("border", "Specifies a border for an element"),
    BORDER_BOTTOM("border-bottom", "Specifies a bottom border for an element."),
    BORDER_BOTTOM_COLOR("border-bottom-color","Sets the color of a bottom border "),
    BORDER_BOTTOM_LEFT_RADIUS("border-bottom-left-radius","Sets the border radius of the bottom left corner."),
    BORDER_BOTTOM_RIGHT_RADIUS("border-bottom-left-radius","Sets the border radius of the bottom right corner."),
    BORDER_BOTTOM_STYLE("border-bottom-style","Sets the style of the bottom border."),
    BORDER_BOTTOM_WIDTH("border-bottom-width","Sets the width of the bottom border"),
    BORDER_LEFT("border-left","Sets the left border of the element."),
    BORDER_LEFT_COLOR("border-left-color","Sets the color of the left border."),
    BORDER_LEFT_STYLE("border-left-style","Sets the style of the left border."),
    BORDER_LEFT_WIDTH("border-left-width","Sets the width of the left border."),
    BORDER_RIGHT("border-left","Sets the right border of the element."),
    BORDER_RIGHT_COLOR("border-right-color","Sets the color of the right border."),
    BORDER_RIGHT_STYLE("border-right-style","Sets the style of the right border."),
    BORDER_RIGHT_WIDTH("border-right-width","Sets the width of the right border."),
    BORDER_TOP("border-top", "Specifies a top border for an element."),
    BORDER_TOP_COLOR("border-top-color","Sets the color of a top border "),
    BORDER_TOP_LEFT_RADIUS("border-top-left-radius","Sets the border radius of the top left corner."),
    BORDER_TOP_RIGHT_RADIUS("border-top-left-radius","Sets the border radius of the top right corner."),
    BORDER_TOP_STYLE("border-top-style","Sets the style of the top border."),
    BORDER_TOP_WIDTH("border-top-width","Sets the width of the top border"),
    BORDER_RADIUS("border-radius","Sets the radius of the border."),
    BORDER_COLLAPSE("border-collapse","Sets table borders to single collapsed line or separated."),
    BORDER_COLOR("border-color","Sets the color of the border."),
    BORDER_IMAGE("border-image","Defines an image as border, instead of a color."),
    BORDER_IMAGE_OUTSET("border-image-outset","Sets how far a border image extends beyond the border."),
    BORDER_IMAGE_REPEAT("border-image-repeat","Defines if and how the border image is repeated."),
    BORDER_IMAGE_SLICE("border-image-slice","Defines how the border image will be sliced."),
    BORDER_IMAGE_source("border-image-source","Specifies the url of the border image file."),
    BORDER_IMAGE_WIDTH("border-image.width","Sets the width of the image border."),
    BORDER_SPACING("border-spacing","Sets the adjacent table cell distance."),
    BORDER_STYLE("border-style","Defines the style of the border"),
    BORDER_WIDTH("border-width","Sets the border width of the element."),
    BOTTOM("bottom","Positions the element from the bottom of the relative container."),
    BOX_SHADOW("box-shadow","Adds a shadow effect to an element."),
    BOX_SIZING("box-sizing","Sets how element height and width are calculated."),
    CAPTION_SIDE("caption-side","Defines on which side of the table a caption is placed."),
    CARET_COLOR("caret-color","Sets the color of the blinking mouse caret."),
    CLEAR("clear","Sets the element side that does not allow floating elements."),
    CLIP("clip","Sets how an image is cropped or clipped inside a container."),
    CLIP_PATH("clip-path","Clips an element inside a specific shape or SVG."),
    COLOR("color","Specifies the color of text in an element."),
    COLUMN_COUNT("column-count","Divides an element into the specified number of columns."),
    COLUMN_FILL("column-fill","Specifies how divided columns are filled."),
    COLUMN_GAP("column-gap","Specifies the space between divided columns."),
    COLUMN_RULE("column-rule","Sets the style, width, and color of a column divider."),
    COLUMN_RULE_COLOR("column-rule-color","Sets the color of a column divider."),
    COLUMN_RULE_STYLE("column-rule-style","Sets the style of a column divider."),
    COLUMN_RULE_WIDTH("column-rule-width","Sets the width of a column divider."),
    COLUMN_SPAN("column-span","Sets number of divided columns an element should span."),
    COLUMN_WIDTH("column-width","Specifies the width of a divided column."),
    COLUMNS("columns","Divide an element into columns of a certain width."),
    CONTENT("content","Used to insert content before or after an element."),
    COUNTER_INCREMENT("counter-increment","Increase or decrease a CSS counter."),
    COUNTER_RESET("counter-reset","Initialize or reset CSS counter."),
    CURSOR("cursor","Specifies the shape of the mouse cursor."),
    DIRECTION("direction","Specifies the text writing direction of a block-level element."),
    DISPLAY("display","Specify an element's display behavior."),
    EMPTY_CELLS("empty-cells","Specifies whether empty table cell borders will be displayed."),
    FILTER("filter","Adds an image enhancing effect to an image."),
    FLEX("flex","Specifies the width of the flexible items."),
    FLEX_BASIS("flex-basis","Specifies the initial width of a flex item."),
    FLEX_DIRECTION("flex-direction","Specifies the direction for the flex item to align."),
    FLEX_FLOW("flex-flow","Controls the direction and wrapping of flexible items."),
    FLEX_GROW("flex-grow","Specifies how a flex item can grow inside the container."),
    FLEX_SHRINK("flex-shrink","Specifies how a flex item can shrink inside the container."),
    FLEX_WRAP("flex-wrap","Specifies how flexible items wrap inside the container."),
    FLOAT("float","Sets how an element is positioned relative to other elements."),
    FONT("font","Sets font family, variant, weight, height, and size for an element."),
    FONT_FAMILY("font-family","Sets the font family for an element."),
    FONT_KERNING("font-kerning","Sets the spacing between the font's characters."),
    FONT_SIZE("font-size","Sets the size of the font for an element."),
    FONT_SITE_ADJUST("font-size-adjust","Specifies a fall-back font size."),
    FONT_STRETCH("font-stretch","Sets the text characters to a wider or narrower variant."),
    FONT_STYLE("font-style","Set the font style to normal, italic, or oblique."),
    FONT_VARIANT("font-variant","Specifies that text is displayed in a small-caps font."),
    FONT_WEIGHT("font-weight","Sets the weight or thickness of the font."),
    GRID("grid","Defines a grid layout with responsive rows and columns."),
    GRID_AREA("grid-area","Sets the size and location of grid items in a grid container."),
    GRID_AUTO_COLUMNS("grid-auto.columns","Specifies the size of the columns in a grid container."),
    GRID_AUTO_FLOW("frid-auto.flow","Specifies the initial placement of items in a grid container."),
    GRID_AUTO_ROWS("grid-auto-rows","Specifies the initial size of the items in a grid container."),
    GRID_COLUMN("frid-column","Specifies the size and location of a grid item in a grid container."),
    GRID_COLUMN_END("grid-column-end","Specifies in which column-line the grid item will end."),
    GRID_COLUMN_GAP("grid-column.gap","Specifies the gap size between columns in a grid container."),
    GRID_COLUMN_START("frid-column-start","Specifies in which column line the grid item will start."),
    GRID_GAP("frid-gap","Specifies the gap size between grid rows and columns."),
    GRID_ROW("grid-row","Specifies the grid item size and location in a grid container."),
    GRID_ROW_END("grid-row-end","Specifies in which row-line the grid item will end."),
    GRID_ROW_GAP("grid-row-gap","Specifies the gap size between rows in a grid container."),
    GRID_ROW_START("grid-row-start","Specifies in which row line the grid item will start"),
    GRID_TEMPLATE("grid-template","Divides a page into sections with a size, position, and layer."),
    GRID_TEMPLATE_AREAS("grid-template-areas","Specifies area in a grid container."),
    GRID_TEMPLATE_COLUMNS("grid-template-columns","Sets the number and width of columns in a grid container."),
    GRID_TEMPLATE_ROWS("grid-template-rows","Sets the number and height of rows in a grid container."),
    HEIGHT("height","Sets the height of an element."),
    HYPHENS("hyphens","Specifies hyphenation with wrap opportunities in a line of text."),
    JUSTIFY_CONTENT("justify-content","Defines the alignment of items in a flex container."),
    LEFT("left","Positions the element from the left of the relative container."),
    LETTER_SPACING("letter-spacing","Sets the spacing between characters."),
    LINE_HEIGHT("line-height","Sets the vertical spacing between lines of text."),
    LIST_STYLE("list-style","Defines the markers (bullet points) for items in a list."),
    LIST_STYLE_IMAGE("list-style-image","Defines an image markers (bullet points) for items in a list."),
    LIST_STYLE_POSITION("list-style-position","Sets the marker (bullet point) positions for items in a list"),
    LIST_STYLE_TYPE("list-style-type","Defines the marker types (bullet points) for items in a list"),
    MARGIN("margin","Sets the margin (outside spacing) for an element."),
    MARGIN_BOTTOM("margin-bottom","Sets the bottom margin (outside spacing) for an element."),
    MARGIN_LEFT("margin-left","Sets the left margin (outside spacing) for an element."),
    MARGIN_RIGHT("margin-right","Sets the right margin (outside spacing) for an element."),
    MARGIN_TOP("margin-top","Sets the top margin (outside spacing) for an element."),
    MAX_HEIGHT("max-height","Sets the maximum height for an element."),
    MAX_WIDTH("max-width","Sets the maximum width for an element."),
    MIN_HEIGHT("min-height","Sets the minimum height for an element."),
    MIN_WIDTH("min-width","Sets the minimum width for an element."),
    OBJECT_FIT("object-fit","Specifies how an image or video fits inside a container."),
    OBJECT_POSITION("object-position","Specifies the image or video position inside a container."),
    OPACITY("opacity","Sets the opacity (transparency) of the element."),
    ORDER("order","Specifies the order of an item in a flex container."),
    OUTLINE("outline","Adds an outline (highlighted border) to an element."),
    OUTLINE_COLOR("outline-color","Sets the color of an outline."),
    OUTLINE_OFFSET("outline-offset","Sets the space between the outline and border."),
    OUTLINE_STYLE("outline-style","Sets the style of an outline."),
    OUTLINE_WIDTH("outline-width","Sets the width of an outline."),
    OVERFLOW("overflow","Specifies the flow of content that exceeds the container."),
    OVERFLOW_X("overflow-x","Specifies the flow of content that exceeds the container width."),
    OVERFLOW_Y("overflow-y","Specifies the flow of content that exceeds the container height."),
    PADDING("padding","Sets the spacing between content and element border."),
    PADDING_BOTTOM("padding-bottom","Sets the spacing between content and bottom element border."),
    PADDING_LEFT("padding-left","Sets the spacing between content and left element border."),
    PADDING_RIGHT("padding-right","Sets the spacing between content and right element border."),
    PADDING_TOP("padding-top","Sets the spacing between content and top element border."),
    PAGE_BREAK_AFTER("page-break-after","Adds a print page-break after an element."),
    PAGE_BREAK_BEFORE("page-break-before","Adds a print page-break before an element."),
    PAGE_BREAK_INSIDE("page-break-inside","Specifies if print page-break is allowed inside an element."),
    PERSPECTIVE("perspective","Adds perspective to a 3D-positioned element."),
    PERSPECTIVE_ORIGIN("perspective-origin","Sets the origin of the perspective for a 3D-positioned element."),
    POINTER_EVENTS("pointer-events","Specifies whether element reacts to pointer events or not."),
    POSITION("position","Sets the element's positioning method."),
    QUOTES("quotes","Defines the quotation marks to be used on text."),
    RIGHT("right","Positions the element from the right of the relative container."),
    SCROLL_BEHAVIOR("scroll-behavior","Specifies the scrolling behavior of an element"),
    TABLE_LAYOUT("table-layout","Aligns elements according to a table with rows and columns."),
    TEXT_ALIGN("text-align","Sets the alignment of text inside an element."),
    TEXT_ALIGN_LAST("text-align-last","Sets the alignment for the last line of text."),
    TEXT_DECORATION("text-decoration","Defines the style and color of underlined text."),
    TEXT_DECORATION_COLOR("text-decoration-color","Defines the color of underlined text."),
    TEXT_DECORATION_LINE("text-decoration-line","Defines the kind of line to use with text."),
    TEXT_DECORATION_STYLE("text-decoration-style","Defines the style of underlined text."),
    TEXT_INDENT("text-indent","Sets the indentation to the beginning of text."),
    TEXT_JUSTIFY("text-justify","Defines the text justification inside a container."),
    TEXT_OVERFLOW("text-overflow","Sets the display behavior of text that overflows a container."),
    TEXT_SHADOW("text-shadow","Adds a shadow effect to text."),
    TEXT_TRANSFORM("text-transform","Defines text capitalization or casing."),
    TOP("top","Positions the element from the top of the relative container"),
    TRANSFORM("transform","Applies a 2D or 3D transformation to an element."),
    TRANSFORM_ORIGIN("transform-origin","Sets the origin for the transformation of the element."),
    TRANSFORM_STYLE("transform-style","Specifies the display behavior of 3D space nested elements."),
    TRANSITION("transition","Creates transitions from one property value to another."),
    TRANSITION_DELAY("transition-delay","Creates a delay before the transition effect starts."),
    TRANSITION_DURATION("transition-duration","Specifies the time the transition will take."),
    TRANSITION_PROPERTY("transition-property)","Specifies the CSS property that will transition."),
    TRANSITION_TIMING_FUNCTION("transition-timing-function","Defines the speed curve function of the transition."),
    USER_SELECT("user-select","Specifies how text can be selected (highlighted)"),
    VERTICAL_ALIGN("vertical-align","Specifies vertical alignment of an element."),
    VISIBILITY("visibility","Specifies the visibility of an element."),
    WHITE_SPACE("white-space","Specifies how white-space is handled inside an element."),
    WIDTH("width","Sets the width of an element."),
    WORD_BREAK("word-break","Specifies how line breaks take place."),
    WORD_SPACING("word-spacing","Sets the spacing between words."),
    WORD_WRAP("word-wrap","Specifies how long words can be wrapped."),
    WRITING_MODE("writing-mode","Sets the text reading orientation: top to bottom, etc."),
    Z_INDEX("z-index","Sets the vertical stacking order relative to other elements.");





    private final String code;
    private final String description;

    CssAttribute(final String code, final String description) {
        this.code = code.toLowerCase();
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public String getDescription() {
        return description;
    }

}
